### ISSUE TITLE
BadMethodCallException

### ISSUE THREAD

**Issue by Marcos-Pablo** [artisanry/leaderboard#18]
When I try to use the methods of your library, I get the following error message, "Call to undefined method", how to call the methods correctly?

**Comment by pxgamer** [comment]
@Marcos-Pablo, have you added the trait to your model? I noticed that this isn't actually mentioned in the docs. For example:
```php
use BrianFaust\Leaderboard\Traits\Boardable;

class User
{
    use Boardable;
}
```

**Comment by faustbrian** [comment]
https://github.com/artisanry/leaderboard/commit/08e3e15f12c916706f908f278b105337b1447e07
